const fullRichTextLong1 = `<div class="seooptimizer__text-info"><p>Si querés<b> pasarte a Personal</b>, podrás hacerlo a través de la portabilidad de un modo muy sencillo. No importa de qué empresa seas, tenés la posibilidad de <b>mantener tu número</b> y cambiarte de compañía.</p><p>Con la portabilidad, no es necesario que cambies el número telefónico y podrás tener el servicio de Personal sin ningún tipo de inconveniente. Finalizarás el contrato con la compañía que te brindaba tu servicio actual y pasarás a ser parte de Personal.</p><p>Hacer la portabilidad es un trámite sencillo. Podés comenzar el trámite de diferentes maneras: <b>WhatsApp, Chat online, o llamada telefónica</b>. También tenés la opción de acercarte a alguna de nuestras oficinas. Primero elegís un plan, luego te llega un PIN por SMS. Como tercer paso, enviás una foto de tu DNI por WhatsApp y, por último, recibís el chip en tu casa (sin ningún costo) para que comiences a disfrutar del servicio.&nbsp;</p><p>El trámite de portabilidad puede demorar como máximo 10 días hábiles <b>dependiendo de tu zona </b>y los tiempos de entrega del chip. Si estás en AMBA son como máximo <b>5 días hábiles</b> y para el resto del país <b>8 días hábiles</b>. Si el trámite lo haces presencial en una sucursal, la portabilidad se hace efectiva al siguiente día hábil.</p></div>`;

const fullRichTextLong2 = `<div class="seooptimizer__text-info"><p>Por tener Personal en el celu y en tu casa, contás con muchos beneficios complementarios que podés aprovechar al instalar la App Mi Personal. Algunos de los principales beneficios Personal a los que podés acceder son: descuentos en tu factura por vincular los servicios; 1 GB de regalo al comprar un pack de datos de 1, 3 o 5 GB, un pase WiFi Pass de 5 GB gratis por 30 días; pases Flow Pass de 10 GB para disfrutar del mejor entretenimiento. Si tenés Línea Prepaga Personal, te llevás $450 de crédito para usar como quieras.</p>
<p>En la App Mi Personal podés vincular servicios Personal, gestionarlos en un mismo lugar y aprovechar los beneficios exclusivos. También podés descargar y pagar facturas; ver consumos y estado de los servicios; comprar datos y recargar crédito.</p>
<p>En Personal, ¡en combo te conviene más! Por tener Internet más una Línea Móvil bajo la misma titularidad, en la Tienda Personal, también accedés a descuentos Personal. Te podés llevar descuentos exclusivos en productos seleccionados o promociones especiales, ¡podés obtener grandes descuentos! Estos descuentos pueden acumularse con otros y los vas a tener impactados al momento de realizar el pago.</p>
</div>`;

const fullRichTextLong3 = `<div class="seooptimizer__text-info"><p>Para quienes son <b>clientes de Personal</b>, hay varios servicios adicionales muy convenientes al momento de realizar tareas y de gran ayuda para dinamizar el trabajo y disfrutar de actividades de entretenimiento. Entre los <b>servicios adicionales Personal</b>, algunas de las opciones más destacadas son las siguientes:</p>
<ul><li><p>Personal Security: este servicio está desarrollado en colaboración con McAfee y permite tener una mejor seguridad al navegar por la web o al abrir archivos en los dispositivos electrónicos.</p>
</li><li><p>Wifi Pass: este servicio permite acceder a los puntos de conexión de Personal WiFi disponibles en las zonas habilitadas. Es una excelente opción para ahorrar datos móviles.</p>
</li><li><p>Flow Pass: si querés ver Flow desde tus dispositivos móviles sin gastar datos, esta es una alternativa muy conveniente que te permite contar con un paquete de GB adicionales durante un periodo determinado.</p>
</li><li><p>Protección Personal Plus: este servicio creado en colaboración con La Caja de ahorro y seguro te permite contar con una cobertura contra el robo o el daño total de tu dispositivo.</p>
</li><li><p>Llamadas 4G: este tipo de llamadas, a diferencia de las tradicionales, ofrecen una mejor calidad de voz y mucha más velocidad. También se puede seguir navegando sin perder señal.</p>
</li><li><p>Llamadas WIFI: este servicio permite realizar y recibir llamadas a través de una conexión por red WIFI.</p>
</li><li><p>RCS chat: este servicio es mucho más eficiente que los SMS tradicionales y ofrece mejores opciones de conectividad.</p>
</li></ul>
<p>En conclusión, Personal te brinda muchas alternativas complementarias que son realmente útiles al momento de comunicarte y realizar muchas otras tareas diversas.</p>
</div>`;

const fullRichTextShort = `<div class="seooptimizer__text-info"><p>Si estás por mudarte y querés seguir manteniendo el mismo servicio de Internet, podés solicitar el <b>cambio de domicilio</b> de un modo muy sencillo.</p></div>`;